### ISSUE TITLE
permission errors

### ISSUE THREAD

**Issue by elieobeid7** [cakephp/upgrade#124]
I got this error by using this

https://github.com/dereuromark/upgrade

```
Set Folder Permissions ? (Default to Y) [Y,n]? y
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp/cache
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp/cache/models
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp/cache/persistent
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp/cache/views
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp/sessions
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp/tests
Permissions set on /home/elie/upgrade/vendor/cakephp/app/tmp
Permissions set on /home/elie/upgrade/vendor/cakephp/app/logs
PHP Fatal error:  Uncaught Error: Class 'Cake\Utility\Security' not found in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php:182
Stack trace:
#0 /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php(84): App\Console\Installer::setSecuritySalt('/home/elie/upgr...', Object(Composer\IO\ConsoleIO))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(297): App\Console\Installer::postInstall(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\Console\\Ins...', 'postInstall', Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(324): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#5 phar:///usr/loc in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php on line 182

Fatal error: Uncaught Error: Class 'Cake\Utility\Security' not found in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php:182
Stack trace:
#0 /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php(84): App\Console\Installer::setSecuritySalt('/home/elie/upgr...', Object(Composer\IO\ConsoleIO))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(297): App\Console\Installer::postInstall(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\Console\\Ins...', 'postInstall', Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(324): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#5 phar:///usr/loc in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php on line 182

```

Why I'm reporting this here? because the other repo closed the issue tracker, what they did is dirty, advertising that their tool works, while it doesn't and they know that very well so that they decided to close the issue tracker.

So maybe here, I find someone who managed to use this tool or that other one or any other tool to migrate versions. I want to migrate from cakephp version 2.1.0 to the latest.

**Comment by dereuromark** [comment]
I think the issue tracker was closed by accident, this is now fixed.
As for your remarks: I recommend not using such a tone - as this is not helpful to the discussion.

For most this tool works fine. If there is some subsection that is not working, then you can help fixing it.
By no means that tool is supposed to be the perfect super-maintained tool - as no one has the resources to promise this. It is designed to be a collaborative helper to ease migration/updating.
Please respect that we also do that all in our free time.

**Comment by dereuromark** [comment]
Don't see folder permissions here as a workaround, as this is neither needed nor desired probably.

**Comment by elieobeid7** [comment]
I respect that, I'm a developer and too and know what it takes to maintain a project. I hate two things

1. Closing the issue tracker, leaving users with no way of getting help
2. Refusing to achieve an old unmaintained repo that has a lot of problems, just because the creator benefits on his CV from the fact that his repo has a lot of stars and likes to show off this. And when you try to use it, no one would help you.  Like [slick slider](https://github.com/kenwheeler/slick)

Having said that, I apologize for my tone, I didn't mean to hurt anyone. 

Regarding the permission, even if I say no, I still get errors, should I dismiss that altogether?

```
Set Folder Permissions ? (Default to Y) [Y,n]? n
PHP Fatal error:  Uncaught Error: Class 'Cake\Utility\Security' not found in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php:182
Stack trace:
#0 /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php(84): App\Console\Installer::setSecuritySalt('/home/elie/upgr...', Object(Composer\IO\ConsoleIO))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(297): App\Console\Installer::postInstall(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\Console\\Ins...', 'postInstall', Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(324): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#5 phar:///usr/loc in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php on line 182

Fatal error: Uncaught Error: Class 'Cake\Utility\Security' not found in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php:182
Stack trace:
#0 /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php(84): App\Console\Installer::setSecuritySalt('/home/elie/upgr...', Object(Composer\IO\ConsoleIO))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(297): App\Console\Installer::postInstall(Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(219): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('App\\Console\\Ins...', 'postInstall', Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#4 phar:///usr/local/bin/composer/src/Composer/Installer.php(324): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#5 phar:///usr/loc in /home/elie/upgrade/vendor/cakephp/app/src/Console/Installer.php on line 182
```

**Comment by dereuromark** [comment]
Yes, as those are not relevant for the tool itself, this is a small side effect of some post hook you do not need.

**Comment by elieobeid7** [comment]
Sorry for bothering you, I got an error

```
➜  upgrade git:(master) bin/cake upgrade all /opt/lampp/htdocs/cms     
PHP Warning:  require(/home/elie/upgrade/vendor/composer/../cakephp/cakephp/src/Core/functions.php): failed to open stream: No such file or directory in /home/elie/upgrade/vendor/composer/autoload_real.php on line 66

Warning: require(/home/elie/upgrade/vendor/composer/../cakephp/cakephp/src/Core/functions.php): failed to open stream: No such file or directory in /home/elie/upgrade/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/home/elie/upgrade/vendor/composer/../cakephp/cakephp/src/Core/functions.php' (include_path='.:/opt/lampp/lib/php') in /home/elie/upgrade/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/home/elie/upgrade/vendor/composer/../cakephp/cakephp/src/Core/functions.php' (include_path='.:/opt/lampp/lib/php') in /home/elie/upgrade/vendor/composer/autoload_real.php on line 66
```

**Comment by dereuromark** [comment]
You need to rerun the above command and skip the permission thing.
Otherwise your autoloader is broken.

Please also dont run all, as documented you should start with small chunks to get a grip on the tool and side effects.
Then slowly understand what the parts do and what effects those have, debug it if you run into issues. Fix issues you can solve via PR please.

I will close this now as this is a bug tracker.

**Comment by elieobeid7** [comment]
This is a bug related to the library

```
Exception: Class 'PHPUnit\Framework\TestCase' not found in [/home/elie/upgrade/vendor/cakephp/cakephp/src/TestSuite/TestCase.php, line 35]
2019-09-05 11:41:25 Error: [Error] Class 'PHPUnit\Framework\TestCase' not found in /home/elie/upgrade/vendor/cakephp/cakephp/src/TestSuite/TestCase.php on line 35
Stack Trace:
#0 /home/elie/upgrade/vendor/composer/ClassLoader.php(444): include()
#1 /home/elie/upgrade/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/home/elie/upgr...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Cake\\TestSuite\\...')
#3 [internal function]: spl_autoload_call('Cake\\TestSuite\\...')
#4 /home/elie/upgrade/src/Shell/Task/AppUsesTask.php(150): class_exists('Cake\\TestSuite\\...')
#5 [internal function]: Cake\Upgrade\Shell\Task\AppUsesTask->Cake\Upgrade\Shell\Task\{closure}(Array)
#6 /home/elie/upgrade/src/Shell/Task/AppUsesTask.php(159): preg_replace_callback('#App::uses\\(\\s*...', Object(Closure), '<?php\n/**\n * Co...', -1, 6)
#7 /home/elie/upgrade/src/Shell/Task/AppUsesTask.php(115): Cake\Upgrade\Shell\Task\AppUsesTask->_replaceAppUses('<?php\n/**\n * Co...')
#8 /home/elie/upgrade/src/Shell/Task/ChangeTrait.php(63): Cake\Upgrade\Shell\Task\AppUsesTask->_process('/opt/lampp/htdo...')
#9 /home/elie/upgrade/src/Shell/UpgradeShell.php(114): Cake\Upgrade\Shell\Task\AppUsesTask->process('/opt/lampp/htdo...')
#10 /home/elie/upgrade/vendor/cakephp/cakephp/src/Console/Shell.php(518): Cake\Upgrade\Shell\UpgradeShell->all('/opt/lampp/htdo...')
#11 /home/elie/upgrade/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(230): Cake\Console\Shell->runCommand(Array, true, Array)
#12 /home/elie/upgrade/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(182): Cake\Console\ShellDispatcher->_dispatch(Array)
#13 /home/elie/upgrade/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php(128): Cake\Console\ShellDispatcher->dispatch(Array)
#14 /home/elie/upgrade/bin/cake.php(21): Cake\Console\ShellDispatcher::run(Array)
#15 {main}

```
